logging.level.victor: DEBUG
#logging.level.root: DEBUG
#logging.pattern.console: "%d{HH:mm:ss.SSS} %-10.10logger{0} %message%n"

zuul:
  routes:
    back:
      url: http://localhost:8080

jwt.secret: secretMare
server:
  port: 80