spring.application.name: gateway-service

server.port: 80
jwt.signature.shared.secret.base64: c2VjcmV0TWFyZQ==



acme-parent: &acme-parent
  owner: "ACME"
  hours:
    start: "8:00"
    end: "21:00"

silicon-parent: &silicon-parent
  owner: "SILICON"
  hours:
    start: "8:00"
    end: "21:00"

show:
  timetable:
    MONDAY: &workDay
      - start: "08:00"
        end: "13:00"
      - start: "14:00"
        end: "19:00"
    TUESDAY: *workDay
    WEDNESDAY: *workDay
    THURSDAY: *workDay
    FRIDAY: *workDay
    SATURDAY: &weekendDay
      - start: "9:00"
        end: "15:00"
    SUNDAY: *weekendDay
#  warehouse:
#    acme1:
#      << : *acme-parent
#      gps: "gps1"
#      hours.end: "24:00"
#    acme2:
#      << : *acme-parent
#      gps: "gps2"
#      hours.end: "24:00"
#    acme3:
#      << : *acme-parent
#      gps: "gps3"
#    silicon1:
#      << : *silicon-parent
#      gps: "gps11"

