logging.level.hello: DEBUG
logging.pattern.console: "%d{HH:mm:ss.SSS} %-10.10logger{0} %message%n"

jwt.secret: secretMare

server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:backend.jks
    key-store-password: parola
    key-alias: spring-backend
    key-password: parola
    key-store-type: JKS
