logging.level.hello: DEBUG
logging.pattern.console: "%d{HH:mm:ss.SSS} %-10.10logger{0} %message%n"

jwt.secret: secretMare

server:
  port: 8081
  ssl:
    key-store: C:\workspace\spring\backend.jks
    key-store-type: JKS
    key-password: parola
    key-alias: backend
    key-store-password: parola


