db.password: 99999


welcome:
  help:
    app-id: 1251
    file: /Users/victorrentea/workspace/spring/spring-start/src/main/resources/application.yml
  supportUrls:
    - http://google.com
    - http://stackoverflow.com
    - http://baeldung.com
    - http://spring.io
  localContactPhone:
    RO: +401312121414
    FR: +430123414123
  welcome-message: Frate! stie intelliJ tata!