john.name: John
welcome:
  welcomeMessage: Welcome to This Spring Realm
  help:
    app-id: 1251
    file: c:/help-file.pdf
  supportUrls:
    - http://google.comOUPS
    - http://stackoverflow.com
    - http://baeldung.com
    - http://spring.io
  localContactPhone:
    RO: +401312121414
    FR: +430123414123
sched.cron: "-"
