

john.name: John
welcome:
  welcomeMessage: Welcome to This Spring Realm
  help:
    app-id: 1251
    file: c:/help-file.pdf
  localContactPhone:
    RO: +401312121414
    FR: +430123414123
  support-urls:
    - http://google.comOUPS
    - http://stackoverflow.com
    - http://baeldung.com
    - http://spring.io
sched.cron: "-"
debug: true


spring:
  datasource:
    hikari:
      connection-init-sql: /init.sql
