customer.name: JohnXX


welcome:
  help:
    appId: 1251
    file: c:/help-file.pdf
  supportUrls: http://google.com,  http://stackoverflow.com,http://baeldung.com,http://spring.io
  localContactPhone:
    RO: +401312121414
    FR: +430123414123
    ES: +asfasfgba
  welcome-message: a
  web-service-endpoints:
    - pass: aaa
      user: aa
      url: http://google.com
      attProvider: victor.training.spring.bean.WelcomeInfo
