
db:
    password: big secret
mail:
    sender: real
spring:
    mail:
        host: smtp.gmail.com
        password: <login password to smtp server>
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: <login user to smtp server>
welcome:
    help:
        app-id: 1251
        file: c:/help-file.pdf
    localContactPhone:
        FR: 430123414123
        RO: 401312121414
    supportUrls:
        - http://google.com
        - http://stackoverflow.com
        - http://baeldung.com
        - http://spring.io
    welcomeMessage: 🥺
    gate: 123

from.email: eu
debug: true