welcome:
  help:
    app-id: 1251
    file: c:/help-file.pdf
  localContactPhone:
    FR: 430123414123
    RO: 401312121414
  supportUrls:
    - http://google.com
    - http://stackoverflow.com
    - http://baeldung.com
    - http://spring.io
  welcomeMessage: 🥺
  gate: 123