welcome:
  welcomeMessage: Welcome to This Spring Realm
  host.port: 9090
  help:
    helpUrl: http://victorrentea.ro
    iconUri: bebe
  supportUrls: google,stackoverflow,baeldung,spring.io
  localContactPhone:
    RO: +401312121414
    FR: +430123414123