#logging.level.root=DEBUG
logging.pattern.console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

spring.jackson:
  serialization.fail-on-empty-beans: false
  deserialization.fail-on-ignored-properties: true

logging.level.com.example: DEBUG

welcome.info: Hello properties
welcome:
  greeting: Hello YAML 3
  help-file: C:\Users\victo\Google Drive\CV+Acte\PFA\Offer - ALL.pdf
  support:
    phone: 999999999,88888888
    email: a@b.com
  tenants:
    - service-class-name: com.example.demo.service.ROService2
      origin: a
      country: ro
    - service-class-name: com.example.demo.service.ROService2
      origin: b
      country: ALL
#    email:
spring.task.execution.pool.core-size: 1
#server.port=0 #aloca port aleator