#logging.level.root=DEBUG
logging.pattern.console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

spring.jackson:
  serialization.fail-on-empty-beans: false
  deserialization.fail-on-ignored-properties: true

logging.level.com.example: DEBUG

welcome.info: Hello properties
welcome:
  greeting: Hello YAML 3
  support:
    phone: 999999999
    email: a@b.com
#    email:
#server.port=0 #aloca port aleator