



welcome:
  welcomeMessage: Welcome to This Spring Realm
  help:
    helpUrl: http://localhost:9090/help
    iconUri: bebe
  supportUrls:
    - google
    - stackoverflow
    - baeldung
    - spring.io
  localContactPhone:
    RO: +401312121414
    FR: +430123414123

