welcome:
  welcomeMessage: Welcome to This Spring Realm
  help:
    helpUrl: http://victorrentea.ro
    iconUri: bebe
  supportUrls: google,stackoverflow,baeldung,spring.io
  localContactPhone:
    RO: +401312121414
    FR: +430123414123
  host-port: 8080



stage.folder: C:\workspace\spring\demo\stage
