wel: Hi from jar.
welcome:
  welcomeMessage: Welcome to This Spring Realm
  help:
    helpUrl: http://baeldung.com
    iconUri: bebe
  supportUrls: http://google.com,http://stackoverflow.com,http://baeldung.com
  localContactPhone:
    RO: +401312121414
    FR: +430123414123



in.folder.path: C:/workspace/spring/demo/in

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
management.endpoint.health.show-components: always