db:
    password: big secret
mail:
    sender: dummy
spring:
    mail:
        host: smtp.gmail.com
        password: <login password to smtp server>
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: <login user to smtp server>
#    datasource:
#        type: Oracle
welcome:
    help:
        file: c:/help-file.pdf
        app-id: 1028
    localContactPhone:
        FR: 430123414123
        RO: 401312121414
    supportUrls:
        - http://google.com
#        - http://stackoverflow.com
#        - http://baeldung.com
#        - http://spring.io
#    welcomeMessage: Welcome to Spring
    gate: 123
pojo:
    a: alfa
    b: beta