db.password: big secret
spring:
#    mail:
#        host: smtp.gmail.com
#        password: <login password to smtp server>
#        port: 587
#        properties:
#            mail:
#                smtp:
#                    auth: true
#                    starttls:
#                        enable: true
#        username: <login user to smtp server>

    datasource:
        type:
#    main:
#        allow-circular-references: true

# injected in WelcomeProps
welcome:
    help:
        app-id: 1251
        file: c:/help-file.pdf
    localContactPhone:
        FR: 430123414123
        RO: 401312121414
    gate: 123
    support-urls:
        - http://google.com
        - http://stackoverflow.com
        - http://baeldung.com
        - http://spring.io
    welcome-message: Hello world!



dinProp: config
# expune mai multe (toate) endpointurile pe /actuator
management:
    endpoints:
        web:
            exposure:
                include: "*"