logging.level.victor: DEBUG
logging.pattern.console: "%d{HH:mm:ss.SSS} %-10.10logger{0} %message%n"

jwt.secret: secretMare
jwt:
  header: JWT-Header
server:
  port: 8080
  ssl:
    #1-ssl
    enabled: true
    key-store: backend.jks
    key-store-password: parola
    key-alias: backend
    key-password: parola
    key-store-type: JKS

    #2-way SSL
    client-auth: need
    trust-store: backend.jks
    trust-store-password: parola
    trust-store-type: JKS


