version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - .:/etc/prometheus

#scopu grafanei in viata e sa arate bine datele pe care le ia din Prometheus + sa trimita alerte cand anumite triggere se intampla
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000