version: '3.8'

services:
  vault:
    image: arm64v8/vault:latest
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=tokenid
      - VAULT_ADDR=http://127.0.0.1:8200
    entrypoint: vault server -dev -dev-listen-address="0.0.0.0:8200" -dev-root-token-id="root"
