logging.level.victor: DEBUG
logging.pattern.console: "%d{HH:mm:ss.SSS} %-10.10logger{0} %message%n"

#the secret should be a base64 encoded value
jwt.secret: c2VjcmV0TWFyZQ==


server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:backend.jks
    key-store-password: password
    key-alias: backend
    key-password: password
    key-store-type: JKS

#    client-auth: need
#    trust-store: classpath:backend.jks
#    trust-store-password: parola
#    trust-store-type: JKS


